server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend_base?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

minio:
  endpoint: http://localhost:9000

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
